ghcr := "ghcr.io/arustydev/zettelkasten-mcp"
dckr := "docker.io/arustydev/zettelkasten-mcp"

# Show available recipes
default:
    @just --list

# Build a specific tool (must match dockerfile prefix)
build tag:
    @docker build --sbom=true --provenance=true --pull --no-cache --platform linux/amd64,linux/arm64 -t "{{ if tag != "" { ghcr + ":" + tag } else { ghcr } }}" -t "{{ if tag != "" { dckr + ":" + tag } else { dckr } }}" -f "{{ justfile_directory() / "Dockerfile" }}" .

# Publish ALL tools at the most recent tag
[parallel]
publish-all: auth
    @just publish http

# Publish a specific tool (must match dockerfile prefix)
[parallel]
publish tag="": (build tag)
    @docker push "{{ if tag != "" { ghcr + ":" + tag } else { ghcr } }}"
    @docker push "{{ if tag != "" { dckr + ":" + tag } else { dckr } }}"

# Authenticate to all Registries
[parallel]
auth:
    @# 'op' is the 1Password CLI
    @echo $(op read op://Developer/ghcr.io/mcp/password) | docker login ghcr.io -u $(op read op://Developer/ghcr.io/mcp/username) --password-stdin
    @docker login -u "$(op read op://Developer/Docker-Hub-MCP/username)" -p "$(op read op://Developer/Docker-Hub-MCP/credential)"
    @rename 's/Dockerfile/dockerfile/g; s/DockerFile/dockerfile/g' -f *

inspect:
    npx -y @modelcontextprotocol/inspector http://localhost:8000/sse 2>&1 | head -50 &)

deploy:
    @docker compose up -d
